project:
  type: website

website:
  title: "SedJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Chapters"
        contents:
          - HerbBiography.qmd
          - HEWThoughts.qmd
          - CrashingLizzie.qmd
          - LRCHistory.qmd
          - Kurdistan.qmd
          - EuPalaeoPioneers.qmd
          - CoringExpedition.qmd
          - MemorableMoments.qmd
          - RedHairHEW.qmd
          - MyrtleMantrap.qmd
          - Klutlan.qmd
          - HEWMemories.qmd
          - COHMAP.qmd
          - BearRat.qmd
          - Bermuda-Florida.qmd
          - HerbGallery.qmd
          - IceManWengen.qmd
          - HEWContributions.qmd
          - HerbNotGone.qmd
          - LRC-reunion2013.qmd
          - HEWCareer.qmd
          - HerbAl.qmd
          - Travelling-with-Herb.qmd
          - EatWright.qmd
          - WrightHE_Publications.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

