project:
  type: website

website:
  title: "SedJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - CrashingLizzie.qmd
          - LRCHistory.qmd
          - EuPalaeoPioneers.qmd
          - CoringExpedition.qmd
          - MemorableMoments.Rmd
          - RedHairHEW.qmd
          - HEWMemories.qmd
          - COHMAP.qmd
          - BearRat.qmd
          - Bermuda-Florida.qmd
          - IceManWengen.qmd
          - WrightHE_Publications.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

