# Herb Wright and COHMAP: 1974-1994

by *Tom Webb* and *John Kutzbach*

It all seems only fitting that Herb was the lead editor for *Global Climates Since the Last Glacial Maximum*, published by the University of Minnesota Press in 1993, and shared in the editorial duties for the COHMAP’s *Science* article in 1988—two of the culminating syntheses of what COHMAP grew into after its humble beginnings in 1974, when we two with Herb and Ed Cushing first broached the subject of cooperating in research at the AMQUA meeting in Madison, inspired by CLIMAP’s model for interdisciplinary and interinstitutional research about Quaternary climates. Although COHMAP, like CLIMAP, fairly soon became international in focus—initially by teaming up with Alayne Street-Perrott, who had begun compiling a global data base of lake-level data—in its original phase, COHMAP proposed to map only the climates and vegetation of eastern North America for the past 16,000 calendar years with a particular focus in central and northeastern US – areas familiar to Herb both from field work, Friends of the Pleistocene trips, and the writing of review articles.

As PhD students under Reid Bryson, we both became intrigued by late Quaternary climates and how the mapped synoptic patterns of past climates had changed in response to various forcings, which came to be represented as a set of changing boundary conditions in global climate models. CLIMAP’s lead in showing the importance of orbital forcing over the past 400,000 years and their modeling of the last glacial maximum world stimulated us to apply their methods and approach to late-Quaternary climates. In doing so, we quickly realized that we needed to expand our focus from the Midwest and eastern North America and assemble global data sets for checking the model results. Herb and colleagues’ work in the Limnological Research Center (LRC) as well as his trans-Atlantic connections made him an excellent collaborator in such a grandiose project. For example, the Huntley and Birks (1983) atlas of European pollen data was an important contribution to the COHMAP global data set, and in the late 1970s, John Birks was an annual visitor at the LRC. In the effort to build a comparable set of pollen data for North America, a strong link to the LRC and Herb’s record of sharing data was crucial. That the Radiocarbon Lab at the Center for Climatic Research would provide dates for LRC cores at low prices was one of many attractions to Herb for teaming up with us. We therefore found a number of mutual benefits to working together right from the get-go.

But it was at the personal level that things took off for us in COHMAP. As one of us (JEK) recalls on first meeting him, “I saw that spark of contagious curiosity that he exhibited and I now recognize how it energized our meetings and scientific discussions. Thinking specifically of climate, but I suspect it applies to all areas, I always had the clear sense that Herb had his own well-thought-out views of how things worked, based on reading and reflection. However, he was always open and asking probing questions to learn more. His quiet questioning of our climatic reasoning helped me to clarify my own thinking and to organize my thoughts into clearer narratives. 

“His vast knowledge of the Quaternary landscape and its evolution always allowed him to expand our thinking to encompass the largest possible geographic and temporal range of ideas and ‘thought models’. For example, we might have had a productive lengthy discussion on a particular region, say the eastern US, and when that topic seemed momentarily exhausted, Herb could gently turn our attention to an entirely different region or time, e.g. the southeast, or the southwest, or Europe or the Middle East, etc. In this amazing way, we always covered a much wider range of topics and ‘uncovered’ new things to think about during our informal small-group discussions that so fueled COHMAP’s emergence as a key program in global climate research.

“I suppose our winter meetings at Herb’s home stick permanently in my mind when I reflect on the milieu in which we worked. I remember how Al Swain took me aside before our first winter meeting and warned me to pack long underwear and layers of sweaters—advice for which I’m still grateful. I recall indoor temperatures well below my comfort level both night and day, and being grateful for the blazing fire. Even so, I think my core temperature lowered gradually over the course of our visits and only fully recovered when I was back home in Madison. 

“I also recall one visit when we arrived about the same time that a large load of wood was being delivered. It seemed completely natural that the first order of business was to get that wood into the house through a basement window, and properly stacked. It’s great to recall how in this case some mundane chore came naturally before thinking, and we had the additional incentive of knowing we would later reap the benefits of warmth. 

“There was a unique pace to life and science in Herb’s home. Breakfast happened gradually with those first smells and taste of tea, of bread in the oven, and so on. Only gradually would we move to the fireside and commence our sessions.  There was also a special deliberate pace to the afternoons and evenings, or evening seminars. Never hurried, but always plenty of time. It was a bit like the slow movement of a symphony, but always with expectation.  I think this patient pace was a part of Herb’s genius for science, and for people, and that a faster tempo would not have been nearly as creative or effective.”

What Herb fostered was a cooperative spirit in doing science and investigating late Quaternary landscapes and environments. We were lucky to share similar interests about past climates and vegetation and to offer complementary skills and training for assembling the data and modeling the processes. During our twenty years of working together in COHMAP, our differing perspectives and knowledge kept us talking and educating each other. All the while, the twinkle in Herb’s eye was there to guide us toward new challenges.
