# Crash Landing of ‘Lizzie’

by Herb Wright and transcribed by Dan Engstrom

This is a transcript of the official report of Herb’s crash landing of his B-17 plane ‘Lizzie’ at St Angelo airfield Enniskillen on 11 February 1944. Dan Engstrom ordered a hard copy of this report in 2009 at Rick Battarbee’s suggestion and then transcribed it. What follows is Dan’s transcription.

## January–February 1944

Jan.26.     Left Pyote on troop train for Grand Island. 25 rubbers of bridge with Sloss, Tribble, and Howe. Two sleepless nights in coaches.

Jan. 28.    Arrived Grand Island. Damp, cool. Atmosphere like Nashville. Fine officers’ club. Processing efficient.

Jan. 31. Signed for one airplane #42-37859 and tested it. Had been in taxi accident, was not the latest model.

Feb. 2.      Ready to take off, but runway blocked by cracked-up ship.

Feb. 4.      Left Grand Island 10:50 for Presque Isle at 17,000 ft \[5180 m\] and 11,000 \[3350 m\] via Omaha, Moline, Toledo, Buffalo, Manchester, and Portland.

Feb. 5.      Snowy hills, crinkling hard-packed snow, sweeping wind, ATG majors, slot machines, poor maintenance.

Feb. 6.      Maintenance woes in the cold.

Feb. 8.      Left Presque Isle for Goose Bay. Beautiful drowned valleys, plateaus, Shickshock Mountains, Notre Dame Mountains, Anticosti. Runways packed with snow. Temperature –10 to –30°F \[–29 to –34°C\]. Wind 10–30 mph \[4.5–13.5 m s^–1^\]. Snowshoeing, skating, freezing.

Feb. 9.      Worked 6 hours to start engines, but #2 was too cold. Back to bed at 6 AM.

Feb. 11.   Took off 10 PM. #2 and #4 oil pressures fluctuated and wouldn’t steady, so landed and checked transmitters. Operation officer said dilution gas hadn’t burned off oil, so we topped up and took off again. Oil pressure remained steady, so we set out. Flight plan at 11,000 ft \[3350 m\], met info proved good. Over ice and clouds for hours, with patches of white-capped water. About 4 hours from ETA, #2 oil pressure began to fluctuate again. Had crossed front at 15,000 ft \[4575 m\], descended to 7000 ft \[2135 m\]. At 11:50 GMT #2 prop governor out, not enough oil for feathering. Still on course, but an hour from the coast of Ireland. Five minutes later #4 began to fluctuate. Increased power on #1 and 3, decreased speed to 135 mph \[215 kmph\], and descended slowly. Knowing that I could get some power out of #4 until prop governor ran away, if it behaved like #2. Oil temp. and cylinder-head temp. normal in both #2 and #4 at all times. Oil sprayed over wings and tail turret. Still on course. Homed in on Ballik Range and Dungeness beacon. Sighted coast through clouds at ca. 12:45 at 6000 ft \[1830 m\], 32”, 2100 rpm on two engines; 2.2”: 1600 rpm on third, 4th windmilling. Could not contact Beleak radio but was directed through overcast by St. Angelo control. No.4 engine prop gov. went during descent, and prop thereafter windmilled. Broke through clouds over field at 2000 ft \[600 m\], but another B-17 was in pattern, so had to make 360 degree turn before approach. Tower had given field elevation instead of altimeter setting. Followed other plane in on high approach, tried to slip, but overshot. Brakes uneven, edged off right side of narrow runway, where there was no traction in the mud. Came to abrupt halt with right gear buried, but intact, up to tip of wheel, and left buried up to hub. Ball turret damaged, nose glass and fixtures damaged, #2, #3, and #4 props bent. No one hurt.

Felt no particular fear we wouldn’t make the coast, for we still had two good engines, even though they were carrying a bit of a load. Nevertheless, it was good to see the islands off the coast. Worried slightly about not contacting Baleek Range, but planned to make it-down regardless. St. Angelo control took over, however, and led us down, bit by bit, along with another plane. Was impatient and much relieved when we broke through the clouds. Had to make a 360 before entering approach to allow another B-17 to land. Consequently the approach was not well planned.

                   Felt a bit stupid after landing. Met a mass of visiting RAF gold braid in the control room, and they were concerned about an obstruction in the runway. A P/O Kirkwood made us at ease fixed us up at the mess and billets.

                   Treated royally by the St. Angelo RAF personnel. Excellent meals. Cold nissen huts for club and quarters. Weak beer but good scotch and Irish whiskey, learned English money, English hospitality cooking, humor.

                   Saturday night drank whiskey with Beaufighter and Sunderland pilots and a Norwegian naval lieutenant.

                   Monday cranes and trucks arrived to lift Lizzie’s nose out of the mud, and we were ferried in another B-17 to Nutt’s Corner ATC station.
