# Where Herb Has Not Yet Gone Before

by *Jim Almendinger*

In honor of Herb’s 90th birthday, which was celebrated in Sils, Switzerland, 2007

In ages long gone, when I started grad school,\
Professors gave simple advice:\
Choose your sites wisely, for only a fool\
Would choose to core a lake twice.

Seek out new sandplains and tills of ablation^1^ –\
There you’ll find lakes you should core.\
Go to new lands and civilizations\
Where no one has yet gone before.

So I drove a ways north and a little ways west\
And sampled a pothole or two.\
With thousands of lakes there, the chances, at best,\
That someone had cored these, were few.

Yet when I came back, I was given a fright:\
My advisor had eyed me with scorn.\
“Those lake have been published by our friend Herb Wright,\
“Who cored them before you were born!”

OK, not a problem, I pushed on ahead\
And chose some lakes out a bit further.\
To prairies I drove, and faster I sped\
To sample the few lakes that were there.

Again I returned, all happy and cheery\
My advisor said, “Sorry to trouble you!!\
“Who first cored those lakes? Have you not a theory?\
“That’s right – it was old HEW!”

Again I resolved to continue my toil,\
In the Canadian Maritimes, where\
After coring, I noticed a scrap of tin foil,\
And I knew that Herb Wright had been there!

In anger I pressed on and went further north;\
The bush pilots thought I was daft.\
But at each site Herb’s residue clearly lay forth,\
Like scraps from an old rubber raft.

I went to the west, far into Alaska\
Where an old timer said with delight,\
“If you’re coring lakes, I think I should ask ya –\
“How is my old friend, Herb Wright?”

I went to the south, to far Patagonia\
To regions not given a name\
Then to shy cloistered corners in old Catalonia,\
But the answer was always the same.

To Egypt, to Sweden, to tiny Swaziland,\
To the southernmost tip of Tasmania,\
To Greenland, to Iceland, and then to New Zealand –\
I madly continued my mania!

I traveled by camel to outer Mongolia,\
To plains that the wind had laid bare.\
To find once again, just like I have told ya,\
That Herb had been already there.

In Persia, Herb cored with one Cyrus the Great\
In Baghdad, with this or that sultan\
For a thousand and one nights, he labored ‘til late\
Writing a paper or bulletin.

He cored in Arabian wadis^2^ with Lawrence;\
He cored in the Sudanese sands.\
He cored with da Vinci some wetlands near Florence\
And on his pants wiped off his hands.

He traveled with Captain James Cook to Hawaii,\
And ate a big sandwich^3^ for lunch.\
And then with his portable coring supply, he\
Cored a salt marsh on a hunch.

He jumped ship in Tahiti^4^ and swam to the shore\
Where the women don’t wear any tops.\
He cored crater lakes, peat bogs, lagoons, and still more – And toasted each one with a schnapps

To the Llanos^5^ he traveled with Bonpland and Humboldt\
To wade in the riverine muck,\
And ended up wrestling with eels full of volts^6^\
While getting his sampler unstuck.

He met up with Darwin^7^ to core a few lakes,\
While Darwin was stumped by his finches.\
When questioned by Herb, Charles saw his mistakes,\
And in gratitude manned the core winches.

Herb’s rod, it was square! His stainless head shone!\
His coring tube’s wall – it was lean!\
Zirconium magnesium made up his bones,\
With aluminum couplings between^8^.

*So…*

I’d traveled the globe, neither heeded nor aided,\
To seek out a lake of my own,\
But only to find, a world perforated\
Like Swiss cheese by Herb’s Livingstone^9^.

I returned in my sorrow, and full of despair.\
What could I do possibly more?\
When a voice from the shadows -- the Devil, I swear!\
Said, “I have a lake you can core...”

“It has a stratigraphy nine layers deep^10^,\
“Core shallow or deep as you choose.\
“But to get an age model, the dates won’t come cheap,\
“From mud of salacious^11^ dark ooze."

“But here is the catch, which some may think nice,\
“To sample continuous sediment.\
“I propose that you wait for a platform of ice,\
“And core there without an impediment.”

So I’m waiting in Hades; I’m tortured, disturbed,\
For sediment I’ve suffered woe for,\
To finally core a lake not cored by Herb,\
When finally, Hell freezes over!

***NOTES:***

^1^Ablation is the melting of glacial ice.

^2^A wadi is a gully, typically dry except in the rainy season, but where oases would be found.

^3^The Hawaiian Islands were once known, of course, as the Sandwich Islands. Cook was the first European to discover the islands in 1778, and died there in 1779 during a conflict with the natives.

^4^If Herb were sailing with Captain Bligh on the HMS *Bounty*, this would have been 1789.

^5^The Llanos are the grassy plains of Venezuela and Columbia along the Orinoco River, visited by Alexander von Humbolt and Aimé Bonpland in 1800.

^6^Humboldt confirmed the existence of electric eels, which live in the muddy pools of the Orinoco.

^7^Darwin was in the Galapagos Islands in 1835; so, too, apparently was Herb.

^8^Herb re-designed the lake-sediment sampler originally designed by Dan Livingstone, introducing a square inner rod, a stainless steel sampler head, a thin (“lean”) walled stainless steel coring tube, and zirconium-magnesium coring rods connected by anodized aluminum couplings.

^9^The modified Livingstone sampler, as described above.

^10^The nine circles of Hell, as described in Dante’s *Inferno*.

^11^In the oceans, the ooze is siliceous; in Hell, salacious.
