# HEW Memories

by *Bob Baker*

I was Herb Wright’s TA for Glacial Geology for several years in the early 1970s and what follows are unique occurrences from his overnight trips.

## The Chicken Dinner from Hell

In the fall of 1971 as the Glacial class was preparing for the first weekend trip, Herb instructed the class to bring appropriate camping gear and indicated that for the dinner Saturday night he would take care of the food and the students could reimburse him after the trip. 

Near the end of a long day, we stopped in Moose Lake, MN to gas up the vehicles and Herb disappeared into the town’s only grocery store.  He eventually emerged carrying two sacks of groceries and a large bag of potatoes.  We left Moose Lake, made one more geology stop and pulled into Jay Cooke State Park after dark – a tradition for the eastern field trip.  Students began setting up camp and several of us unpacked the groceries Herb had purchased in Moose Lake.  We discovered all the fixings for salad, lettuce, celery, tomatoes, etc., salad dressing, and to our surprise, about 12 whole chickens!  So here we were, well after sunset, with no charcoal for cooking potatoes or chicken and no knives to cut up the chicken.  After foraging for firewood, we got a fire built in one of the grills at the campsite, while several students made a huge salad that, in the absence of a mixing bowl was placed in a brown paper grocery bag.  The whole chickens were put on the grill, along with a number of potatoes.  Sometime between 10:30 and 11:00 p.m., with the chicken still not completely cooked, I gave up and crawled into my tent for some needed sleep.  I heard in the morning that a few brave souls gave up on the chicken ever being cooked properly and ate it anyway, without adverse consequences.  Others followed my lead and went to bed having eaten salad only.

The next year Herb told me to take care of the food on this trip and I decided to make a huge pot of campfire chili, which, I was told, became a tradition for future overnight field trips that continued for a number of years.

## Texturing Till

In the fall of 1973, in addition to the usual mix of students enrolled in Herb’s Glacial class, there were several soil science students.  Whenever we stopped to examine a road cut, the soil science students would frequently challenge Herb in texturing the glacial sediments.  The students would use their well-calibrated fingers to texture and Herb would put a small amount of sediment in his teeth, which to everyone’s amazement were just as accurate. 

On our western trip to the Minnesota River Valley, we stopped in the town of St. Rosa to look at an esker with a distinctive chocolate-brown till cap.  When we arrived at the exposure, Herb asked the class about the texture of the till cap, and some of the students picked up small amounts of till and began texturing it with their fingers.  After a few minutes, Herb asked a student to give him a sample of the till.  The student took his rock hammer, dug around in the till, and handed Herb a chunk on the end of the hammer.  Herb put the lump of till in his mouth and after chewing it for a few seconds, to everyone’s amazement, swallowed it whole!  Herb then proclaimed, “that’s pretty good till, do you have any more?” The student obliged and produced another good sized till chunk on his hammer.  Herb, once again wolfed it down.  At this point a number of students followed Herb’s lead and began texturing the till with their teeth.  I distinctly remember hearing the sound of feldspar grains cleaving in student’s teeth and many looked like youngsters who had been eating mud pies, with till smeared from ear to ear.

Several years later I mentioned this episode to Herb and he admitted to me that the “till” samples handed to him on the rock hammer were actually brownies and that the entire episode was a well-choreographed setup.  I am sure that there are students who witnessed that event, who to this day are convinced Herb Wright consumed 4 to 5 ounces on glacial till, pebbles and all.

## The Tube Tent

One of the characteristics of Herb Wright I always admired was his amazing tolerance for extreme weather conditions.  No matter how cold, windy, or rainy it was, Herb always seemed oblivious to the elements.

After completing my degree at the University of Minnesota I began a long career teaching at the University of Wisconsin-River Falls.  In the spring of 1982, I attended the Midwest Friends of the Pleistocene field trip in Burlington, IA with Herb, Ed Cushing, and one of Ed’s graduate students.  We camped at Geode State Park and slept under the stars the first night because the conditions were wonderful and no tents were needed. The second night when we arrived at our campsite, rather late after a banquet and a long program, we could see a storm rapidly approaching and decided to set up tents.  I got mine set up and Herb was still playing around with his.  I asked Herb if he needed assistance or wanted to share my tent and he stubbornly said that he had been given a new tube tent for Christmas and that setup should be simple.  I crawled into my tent and shortly all hell broke loose with lightning, deafening thunder, torrential rain, and hail.  The next morning I when I got up I discovered Herb sleeping in the vehicle.  He explained that he never figured out how to set up the tube tent before the storm hit, so he simply slipped it over his sleeping bag, much like one might do with a large garbage bag, and attempted to ride out the storm.  He said the hail bouncing off his eye sockets and teeth were tolerable, but the last straw was that the tube tent had completely filled with water because he was lying on a slope.  That was when I discovered that although Herb could tolerate almost any weather conditions, he drew the line at sleeping in the equivalent of a bathtub full of water.
