# The Ice Man of Wengen

by Jim Almendinger

Some scientists met atop a Swiss mount

For discussion of lakes and of pollen

And of gravel and ice, and things one can count

That into a peatland have fallen.

And as they discussed global transport of dust,

The climate grew just a bit hotter,

And a huge glacier groaned and fractured its crust,

Receding in streams of meltwater.

Exposed to the sun in a subglacial crack

Lay a curled up form, calm and docile.

A scientist rushed forward and yelled to the pack:

“It looks like a huge macrofossil!”

As they looked at the form in the subglacial groove

They saw that indeed it was human!

Astonished, they gasped as it started to move,

And it yawned, like a pink flower bloomin’!!

Upon his broad back was a lumberjack coat

Of wool that was tattered and ripped.

He coughed just a bit, and then cleared his throat

And pulled out a worn manuscript.

“I was trapped long ago in the deep snowy white!”

He said as he blinked his eyes twice.

“But since I was there, I thought I should write

“Of the things that I saw in the ice.”

“I watched moraines form from the lateral scree,

“And watched air be trapped into bubbles.

“I saw strata of bedload and other debris

“And wrote it all up, without troubles.”

The scientists couldn’t believe this surprise,

As they looked on this white-bearded man

Who calmly gazed out through his icy-blue eyes

And scratched his bald pate with his hand.

The scientists thought they should publish his script,

And each wanted to add just a scrap

To make a long list of co-authors that nipped

The record long held by COHMAP.

They needed a name at the top of the page

To give credit where credit was due.

But the Ice Man with carbon of infinite age

Had scrawled just a lone “W.” 

The scientists thought they should give him a name

That started, at least, with that letter.

The names “Wrong” and “Wright” were both in the game;

In the end, they thought “Wright” would be better. 

To go with his name, they added initials.

They chose “H” and “E” to be clever.

Though the name “H.E. Wright” then appeared quite official

They knew “H.E.” meant “Hardly Ever.” 

But the name “Hardly Ever” was looked at askance;

It just wasn’t nice to disturb.

So they thought of a name that related to plants

And decided upon the name “Herb.”

And that is the story, when all’s said and done

Of the meeting upon alpine heights,

And of all of the work and of all of the fun,

And the Ice Man of Wengen, Herb Wright!!

*-- In honor of Herb’s 80th birthday, which was celebrated in Wengen, Switzerland, 1997 --*

*Jim Almendinger*
