# Publications of Herbert E Wright

compiled by Cathy Jenks and John Birks

**1943**

Wright HE. Cerro Colorado, an isolated non-basaltic volcano in central New Mexico. *Bulletin of the Geological Society of America* 241: 43-56.

**1946**

Wright HE. Sand grains and periglacial climate: a review. *Journal of Geology* 54: 200-205.

Wright HE. Tertiary and Quaternary geology of the Lower Rio Puerco Area, New Mexico. *Geological Society of America Bulletin* 57: 383-456.

**1947**

Wright HE. Marine terraces of the coast of Lebanon. *Geological Society of America Bulletin* 58: 1242.

**1951**

Wright HE. Geologic setting of Ksar 'Akil, a Paleolithic site in Lebanon: preliminary report. *Journal of Near Eastern Studies* 10: 115-119.

Wright HE. Opal cement in thick Tertiary eolian sandstone, Chuska Mountains, Arizona-New Mexico. *Geological Society of America Bulletin* 62: 1492.

Wright HE and Becker RM. Correlation of Jurassic formations along Defiance monocline, Arizona-New Mexico. *American Association of Petroleum Geologists Bulletin* 35: 607-614.

**1952**

Wright HE. Cary and Mankato glaciation in central and northeastern Minnesota. *Geological Society of America Bulletin* 63: 1316.

Wright HE. The geological setting of four prehistoric sites in northeastern Iraq. *Bulletin of the American Schools of Oriental Research* 128: 11-24.

**1953**

Wright HE. Glacial history of the Mentasta Mountains, southeastern Alaska Range. *Geological Society of America Bulletin* 64: 1495.

Wright HE. Interbedded Cary drifts near Minneapolis, Minnesota. *Journal of Geology* 61: 465-471.

Wright HE.  Symposium. Dating the Past.  Geologic dating and the timescale of the ice age.  *Minnesota Academy of Science Proceedings* 21: 42-46.

**1954**

Wright HE. Problem of Tohatchi formation, Chuska Mountain, Arizona-New Mexico. *American Association of Petroleum Geologists Bulletin* 38: 1827-1834.

Wright HE. News & Notes: Friends of the Pleistocene. *Science* 120: 332-332.

**1955**

Wright HE. Valders drift in Minnesota. *Journal of Geology* 63: 403-411.

**1956**

Wright HE. Origin of the Chuska sandstone, Arizona-New Mexico - A structural and petrographic study of a Tertiary eolian sediment. *Geological Society of America Bulletin* 67: 413-434.

Wright HE. Sequence of glaciation in eastern Minnesota. *Geological Society of America Guidebook, Minneapolis Meeting Guidebook* Field Trip 3: 1-24.

Wright HE and Rubin M. Radiocarbon dates of Mankato drift in Minnesota. *Science* 124: 625-626.

**1957**

Appeldorn CR and Wright HE. Volcanic structures in the Chuska Mountains, Navajo Reservation, Arizona-New Mexico. *Geological Society of America Bulletin* 68: 445-468.

Wright HE. Geology. In: Taylor W (ed.) *The Identification of Non-Archaeological Materials*. Washington: National Academy of Sciences Publication 565, 50-51.

Wright HE. Radiocarbon dates of Mankato drift in Minnesota. *Science* 125: 1038-1039.

Wright HE. Stone orientation in the Wadena drumlin field, Minnesota. *Geografiska Annaler* 39: 19-31.

Wright HE. The Late-Glacial chronology of Europe - a discussion. *American Journal of Science* 255: 477-480.

**1958**

Wright HE. Geologic dating in prehistory. *Archaeology* 11: 19-25.

Wright HE (translation of Troll, C. 1944). *Structure soils, solifluction, and frost climates of the earth (Strukturböden, Solifluktion, und Frostklimate der Erde),* Wilmette, Illinois: US Army Snow, Ice, and Permafrost Establishment, Corps of Engineers.

**1959**

Arneman HF and Wright HE. Petrography of some Minnesota tills. *Journal of Sedimentary Petrology* 29: 540-554.

Wright HE, (translation of Büdel, J. 1951). Climatic zones of the Pleistocene (Die Klimazonen des Eiszeitalters). *International Geology Review* 1: 72-79.

Wright HE and Alt D, (translation of Büdel, J. 1953). The 'periglacial'-morphological effects of the Pleistocene climate over the entire world (Die 'periglazial'-morphologische Wirkungen de Eiszeitklimas auf der ganzen Erde). *International Geology Review* 1: 1-16.

**1960**

Wright HE. Climate and prehistoric man in the eastern Mediterranean. In: Braidwood RJ and Howe B (eds) *Prehistoric Investigations in Iraqi Kurdistan.* Chicago: University of Chicago Press, 71-97.

**1961**

Fries M, Wright HE and Rubin M. A late Wisconsin buried peat at North Branch, Minnesota. *American Journal of Science* 259: 679-693.

Wright HE. Late Pleistocene climate of Europe: a review. *Geological Society of America Bulletin* 72: 933-984.

Wright HE. Late Pleistocene soil development, glaciation, and cultural change in the eastern Mediterranean region. *Annals of the New York Academy of Sciences* 95: 718-728.

Wright HE. Pleistocene glaciation in Kurdistan. *Eiszeitalter und Gegenwart* 12: 134-164.

**1962**

Wright HE. Role of the Wadena lobe in the Wisconsin glaciation of Minnesota. *Geological Society of America Bulletin* 73: 73-100.

**1963**

Bent AM and Wright HE. Pollen analysis of surface materials and lake sediments from the Chuska Mountains, New Mexico. *Geological Society of America Bulletin* 74: 491-500.

van Zeist W and Wright HE. Preliminary pollen studies of Lake Zeribar, Zagros Mountains, southwestern Iran. *Science* 140: 65-67.

Watson RA and Wright HE. Landslides on the east flank of the Chuska Mountains, northwestern New Mexico. *American Journal of Science* 261: 525-548.

Wright HE. Climatic change in the Zagros Mountains - revisited. In: Braidwood LS, Braidwood RJ, Howe B, et al. (eds) *Prehistoric Archaeology Along the Zagros Flanks.* Chicago: Oriental Institute, 505-506.

Wright HE and Patten HL. The pollen sum. *Pollen et Spores* 5: 445-450.

Wright HE, Winter TC and Patten HL. Two pollen diagrams from southeastern Minnesota: problems in the regional late-Glacial and Postglacial vegetational history. *Geological Society of America Bulletin* 74: 1371-1396.

**1964**

Farnham RS, McAndrews JH and Wright HE. A late-Wisconsin buried soil near Aitkin, Minnesota, and its paleobotanical setting. *American Journal of Science* 262: 393-412.

Wright HE. Aspects of the early post-glacial forest succession in the Great Lakes region. *Ecology* 45: 439-448.

Wright, H.E. Late Quaternary climates and early Man in the mountains of Kurdistan. In: *Report of the VI International Congress on Quaternary, Volume 2: Palaeoclimatological Section*, Łódź, Warsaw, 341-348.

Wright HE. Origin of the lakes in the Chuska Mountains, northwestern New Mexico. *Geological Society of America Bulletin* 75: 589-597.

Wright HE. The classification of the Wisconsin glacial stage. *Journal of Geology* 72: 628-637.

**1965**

Cushing EJ and Wright HE. Hand-operated corers for lake sediments. *Ecology* 46: 380-384.

Wright HE. Origin of the lakes in the Chuska Mountains, northwestern New Mexico: Reply. *Geological Society of America Bulletin* 76: 269-270.

Wright HE and Frey DG (eds)*. The Quaternary of the United States. A review volume for the VII Congress of the International Association for Quaternary Research*. Princeton, NJ: Princeton University Press, 922 pp.

Wright HE and Ruhe RV. Glaciation of Minnesota and Iowa. In: Wright HE and Frey DG (eds) *The Quaternary of the United States*, Princeton, NJ: Princeton University Press, 29-41.

Wright HE, Livingstone DA and Cushing EJ. Coring devices for lake sediments. In: Kummell B and Raup DM (eds) *Handbook of Paleontological Techniques.* San Francisco: WH Freeman, 494-520.

**1966**

Watts WA and Wright HE. Late-Wisconsin pollen and seed analysis from the Nebraska Sandhills. *Ecology* 47: 202-210.

Wright HE. Stratigraphy of lake sediments and the precision of the paleoclimatic record. In: Sawyer JS (ed) *World Climate from 8000 to 0 BC.* London: Royal Meteorological Society, 157-173.

Wright HE. Book review: Pleistocene Geography. *Ecology* 47: 335-336.

Wright HE and Howell C (eds). Quaternary Studies. Proceedings of the VII Congress of the International Association for Quaternary Research. *Quaternaria*, 314 pp.

Wright HE, Spross B and Watson RA. Pollen analyses of the sediment from sinkhole ponds in the central Kentucky karst. *Bulletin of the National Speleological Society* 28: 185-188.

**1967**

Cushing EJ and Wright HE (eds). *Quaternary Paleoecology*. *Proceedings of the VII Congress of the International Association for Quaternary Research.* New Haven: Yale University Press, 440 pp.

Cushing EJ and Wright HE. Introduction. In: Cushing EJ and Wright HE (eds). *Quaternary Paleoecology*. *Proceedings of the VII Congress of the International Association for Quaternary Research.* New Haven: Yale University Press, 1-8.

Martin PS and Wright HE (eds). *Pleistocene Extinctions*. The Search for a Cause. *Proceedings of the VII Congress of the International Association for Quaternary Research.* New Haven: Yale University Press, 453 pp.

Matsch CL and Wright HE. The southern outlet of Lake Agassiz. In: Mayer-Oakes WJ (ed) *Life, Land, and Water.* Winnipeg: University of Manitoba, 121-140.

Morrison RB and Wright HE (eds). *Quaternary Soils*. *Proceedings of the VII Congress of the International Association for Quaternary Research.* Desert Research Institute, University of Nevada, 338 pp.

Osburn WH and Wright HE (eds). *Arctic and Alpine Environments. Proceedings of the VII Congress of the International Association for Quaternary Research.* Bloomington: Indiana University Press, 308 pp.

van Zeist M and Wright HE. Über probleme der Vegetation und Pollenanalyse in Minnesota und angrenzenden gebieten (USA). In: Tüxen R (ed) *Pflanzensoziologie und Palynologie.* Netherlands: Springer, 121-133.

Wright HE. A square-rod piston sampler for lake sediments. *Journal of Sedimentary Petrology* 37: 975-976.

Wright HE. The use of surface samples in Quaternary pollen analysis. *Review of Palaeobotany and Palynology* 2: 321-330.

Wright HE and Osburn WH. Introduction. In: *Arctic and Alpine Environments. Proceedings of the VII Congress of the International Association for Quaternary Research* Bloomington: Indiana University Press, v-ix.

Wright HE, McAndrews JH and van Zeist W. Modern pollen rain in West Iran, and its relation to plant geography and Quaternary vegetational history. *Journal of Ecology* 55: 415-443.

**1968**

Morrison RB and Wright HE (eds). *Means of Correlation of Quaternary Successions*. *Proceedings of the VII Congress of the International Association for Quaternary Research.* University of Utah Press, 631 pp.

Wright HE. Climatic change in Mycenean Greece. *Antiquity* 42: 123-127.

Wright HE. History of the prairie peninsula. In: *The Quaternary of Illinois.* University of Illinois College of Agriculture Special Publication 14, 78-88.

Wright HE. The natural environment of early food production north of Mesopotamia. *Science* 161: 334-339.

Wright HE. The roles of pine and spruce in the forest history of Minnesota and adjacent areas. *Ecology* 49: 937-955.

Wright HE and Bent AM. Vegetation bands around Dead Man Lake, Chuska Mountains, New Mexico. *American Midland Naturalist* 79: 8-30.

**1969**

Florin M-B and Wright HE. Diatom evidence for the persistence of stagnant glacial ice in Minnesota. *Geological Society of America Bulletin* 80: 695-704.

McAndrews JH and Wright HE. Modern pollen rain across Wyoming basins and northern Great Plains (USA). *Review of Palaeobotany and Palynology* 9: 17-43.

Osburn WH and Wright HE (eds). *Arctic and Alpine Environments*. *Proceedings of the VII Congress of the International Association for Quaternary Research.* Indiana University Press, 308 pp.

Watson RA and Wright HE. The Saidmarreh landslide, Iran. *Geological Society of America Special Paper* 123: 115-139.

Wright HE (ed). *Quaternary Geology and Climate*. *Proceedings of the VII Congress of the International Association for Quaternary Research.* National Academy of Sciences, 310 pp.

Wright HE. Glacial fluctuations and the forest succession in the Lake Superior Area. *Proceedings of the 12th Conference of the International Association for Great Lakes Research.* Ann Arbor, 397-405.

Wright HE. Book review: Water, Weather, and Prehistory, by Robert Raikes. *American Anthropologist* 71: 159-161.

Wright HE and Watts WA with contributions by Waddington JCB, Jelgersma S, Ogawa J and Winter TC. Glacial and vegetational history of northeastern Minnesota. *Minnesota Geological Survey* SP-11: 1-59.

**1970**

Wasylikowa K and Wright HE. Late-glacial plant succession on an abandoned drainageway, northeastern Minnesota, USA. *Acta Palaeobotanica* 2: 23-43.

Wright HE. Environmental changes and the origin of agriculture in the Near East. *BioScience* 20: 210-217.

Wright HE. Vegetational history of the Central Plains. In: Dort W and Jones IK (eds) *Pleistocene and Recent Environments of the Central Great Plains.* Lawrence: Department of Geology, University of Kansas Special Publication 3, 157-172.

Wright HE, Mattson LA and Thomas JA. Geology of the Cloquet Quadrangle, Carlton County, Minnesota. *Geological Map Series* 3: 1-30.

**1971**

Wright HE. Late Quaternary vegetational history of North America. In: Turekian KK (ed) *The Late Cenozoic Glacial Ages.* New Haven: Yale University Press, 425-464.

Wright HE. Retreat of the Laurentide ice sheet from 14,000 to 9000 years ago. *Quaternary Research* 1: 316-330.

**1972**

Loy WG and Wright HE. The physical setting. In: McDonald WA and Rapp G (eds) *The Minnesotan Messinia Expedition: Reconstructing a Bronze Age Environment.* Minneapolis: University of Minnesota Press, 36-46.

Wright HE. Interglacial and postglacial climates: the pollen record. *Quaternary Research* 2: 274-282.

Wright HE. Physiography of Minnesota. In: Sims PK and Morey GB (eds) *Geology of Minnesota: A Centennial Volume.* St Paul: Minnesotan Geological Survey, 561-580.

Wright HE. Quaternary history of Minnesota. In: Sims PK and Morey GB (eds) *Geology of Minnesota: A Centennial Volume.* St Paul: Minnesota Geological Survey, 515-548.

Wright HE. Vegetation history. In: McDonald WA and Rapp G (eds) *The Minnesotan Messinia Expedition: Reconstructing a Bronze Age Environment.* Minneapolis: University of Minnesota Press, 188-199.

**1973**

Heinselman ML and Wright HE. Preface to The ecological role of fire in natural conifer forests of western and northern North America. *Quaternary Research* 3: 317-318.

Wright HE. Quaternary science and public service. *Quaternary Research* 3: 515-519.

Wright HE. Tunnel valleys, glacial surges, and subglacial hydrology of the Superior lobe, Minnesota. *Geological Society of America Memoir* 136: 251-276.

Wright HE and Heinselman ML. Introduction to The ecological role of fire in natural conifer forests of western and northern North America. *Quaternary Research* 3: 319-328 (reprinted in 2014 in *Fire Ecology* 10: 4-13).

Wright HE, Bent AM, Hansen BS, et al. Present and past vegetation of the Chuska Mountains, northwestern New Mexico. *Geological Society of America Bulletin* 84: 1155-1180.

Wright HE, Matsch CL and Cushing EJ. Superior and Des Moines lobes. *Geological Society of America Memoir* 136: 153-185.

**1974**

Banerjee SK, Bogdan D, Engstrom J, et al. Continuous high-resolution profile of the geomagnetic field from approximately 855 BP back to 2255 BP. *Transactions of the American Geophysical Union* 55: 1108.

Waddington JCB and Wright HE. Late-Quaternary vegetational changes on the east side of Yellowstone Park, Wyoming. *Quaternary Research* 4: 175-184.

Wright HE. Landscape development, forest fires, and wilderness management. *Science* 186: 487-495.

Wright HE. The environment of early Man in the Great Lakes region. In: Johnson E (ed) *Aspects of Upper Great Lakes Anthropology; Papers in honor of Lloyd A Wilford.* St Paul: Minnesota Historical Society, 8-14.

**1975**

Wright HE. Book Review: Quaternary history of Sangamon River drainage system, central Illinois, by J.A. Miller. *American Anthropologist* 77: 675.

**1976**

CLIMAP Project Members. The surface of the ice-age earth. *Science* 191: 1131-1137.

Rust RH, Finney HR, Hanson LD and Wright HE. High-altitude photography in the development of a generalized soil map. *Soil Science Society of America Journal* 40: 405-409.

Wright HE. Ice retreat and revegetation in the Western Great Lakes area. In: Mahaney WC (ed) *Quaternary Stratigraphy of North America.* Stroudsberg: Dowden, Hutchinson and Ross Inc., 119-132.

Wright HE. Pleistocene ecology - some current problems. *Geoscience and Man* 13: 1-12.

Wright HE. The dynamic nature of Holocene vegetation: a problem in paleoclimatology, biogeography, and stratigraphic nomenclature. *Quaternary Research* 6: 581-596.

Wright HE. The environmental setting for plant domestication in the Near East. *Science* 194: 385-389.

Wright HE. Book review: Applied geology and archaeology: The Holocene history of Wyoming, by Michael Wilson. *American Anthropologist* 78: 708.

Wright HE and Stein JK. Glacial surges and flood legends. *Science* 193: 1268-1269.

**1977**

Banerjee SK, Lund S, Eyster-Smith NM, et al. Correlation between paleoclimate and paleomagnetism for the last 9,300 years. *Transactions of the American Geophysical Union* 58: 695.

Lund S, Banerjee SK, Levi S, et al. High-resolution paleomagnetic fluctuations from Minnesota - correlation with paleoclimatic data. *Transactions of the American Geophysical Union* 58: 708-709.

Winter TC and Wright HE. Paleohydrologic phenomena recorded in lake sediments. *EOS, American Geophysical Union* 58: 188-196.

Wright HE. Environmental change and the origin of agriculture in the Old and New Worlds. In: Reed CA (ed) *Origins of Agriculture.* The Hague: Mouton Publishers, 281-318.

Wright HE. Quaternary vegetation history - some comparisons between Europe and America. *Annual Review of Earth and Planetary Science* 5: 123-158.

**1979**

Amundson DA and Wright HE. Forest changes in Minnesota at the end of the Pleistocene. *Ecological Monographs* 49: 1-16.

**1980**

Watson RA and Wright HE. The end of the Pleistocene: a general critique of chronostratigraphic classification. *Boreas* 9: 153-162.

Wright HE (ed). Special Issue: Klutlan Glacier. *Quaternary Research* 14, 168 pp.

Wright HE. Climatic change and plant domestication in the Zagros Mountains. *IRAN* 18: 145-148.

Wright HE. Cores of soft lake sediments. *Boreas* 9: 107-114.

Wright HE. Environmental history of the Junín Plain and the nearby mountains. In: Rick JW (ed) *Prehistoric Hunters in the High Andes.* New York: Academic Press, 253-256.

Wright HE. Surge moraines of the Klutlan Glacier, Yukon Territory, Canada - Origin, wastage, vegetation succession, lake development, and application to the late-glacial of Minnesota. *Quaternary Research* 14: 2-18.

**1981**

Ashworth AC, Schwert DP, Watts WA and Wright, HE. Plant and insect fossils at Norwood in south-central Minnesota - a record of late-glacial succession. *Quaternary Research* 15: 113-125.

CLIMAP Project Members. Seasonal reconstructions of the Earth's surface at the last glacial maximum. *Geological Society of America Map and Chart Series* MC-36.

Glaser PH, Wheeler GA, Gorham E and Wright HE. The patterned mires of the Red Lake peatland, northern Minnesota: vegetation, water chemistry and landforms. *Journal of Ecology* 69: 575-599.

Wright HE. Climatic change in the Zagros Mountains - revisited. In: Braidwood LS, Braidwood RJ and Howe B (eds) *Prehistoric Archeology Along the Zagros Flanks.* Chicago: Oriental Institute, 505-509.

Wright HE. Early postglacial problems in Minnesota paleolimnology. *Striae* 14: 94-97.

Wright HE. Holocene chronostratigraphy for United States and Canada. *Striae* 16: 53-55.

Wright HE. The role of fire in land/water interactions. In: Mooney HA, Bonnickson TM, Christiansen NL, et al. (eds) *Fire Regimes and Ecosystem Properties.* US Forest Service General Technical Report 26, 421-444.

Wright HE. Vegetation east of the Rocky Mountains 18,000 years ago. *Quaternary Research* 15: 113-125.

**1982**

Wright HE. (1982) Lake and wetland sediments as records of past atmospheric composition. In: Goldberg ED (ed) *Atmospheric Chemistry.* Berlin: Springer, 135-157.

**1983**

Foster DR, King GA, Glaser PH and Wright HE. Origin of string patterns in boreal peatlands. *Nature* 306: 256-258.

Glaser PH and Wright HE. Book Review: Mires of the World, by A.J.P. Gore. *Ecology* 64: 1666-1667.

Webb T, Cushing EJ and Wright HE. Holocene changes in the vegetation of the Midwest. In: Wright HE (ed) *Late-Quaternary Environments of the United States. Volume 2: The Holocene.* Minneapolis: University of Minnesota Press, 142-165.

Wright HE (ed). *Late Quaternary Environments of the United States* (2 volumes). Minneapolis: University of Minnesota Press, 407 and 277 pp.

Wright HE (ed). *Late Quaternary Environments of the United States*. *Volume 2: The Holocene*. Minneapolis: University of Minnesota Press, 277 pp.

Wright HE. Introduction. In: Wright HE (ed). *Late Quaternary Environments of the United States*. *Volume 2: The Holocene*. Minneapolis: University of Minnesota Press, xi-xvii.

Wright HE. Late-Pleistocene glaciation and climate around the Junín Plain, central Peruvian highlands. *Geografiska Annaler* 65A: 35-43.

Wright HE and Glaser PH. Postglacial peatlands of the Lake Agassiz Plain, northern Minnesota. *Geological Association of Canada Special Paper* 26: 375-389.

**1984**

Engstrom DR and Wright HE. Chemical stratigraphy of lake sediments as a record of environmental change. In: Haworth EY and Lund JWG (eds) *Lake Sediments and Environmental History.* Leicester: University of Leicester Press, 11-67.

Hansen BCS, Wright HE and Bradbury JP. Pollen studies in the Junín area, central Peruvian Andes. *Geological Society of America Bulletin* 95: 1454-1465.

Velichko AA, Wright HE and Barnosky CW (eds). *Late Quaternary Environments of the Soviet Union*. Minneapolis: University of Minnesota Press, 327 pp.

Wright HE. Answer to Hastenrath's comments on 'Late-Pleistocene glaciation and climate around the Junin Plain, central Peruvian highlands. *Geografiska Annaler Series A, Physical Geography* 66: 395-397.

Wright HE. Late Glacial and late Holocene moraines in the Cerros Cuchpanga, central Peru. *Quaternary Research* 21: 275-285.

Wright HE. Paleocology, climatic change, and Aegean prehistory. In: Wilkie NC and Coulson WDE (eds) *Contributions to Aegean Prehistory. Studies in Honor of William A McDonald.* Dubuque, Iowa: Kendall Hunt Publishing Co., 183-195.

Wright HE. Sensitivity and response time of natural systems to climatic change in the late Quaternary. *Quaternary Science Reviews* 3: 91-131.

Wright HE and Barnosky CW. Introduction to the English edition. In: Velichko AA, Wright HE and Barnosky CW (eds). *Late Quaternary Environments of the Soviet Union*. Minneapolis: University of Minnesota Press, xiii-xxii.

Wright HE, Mann DH and Glaser PH. Piston corers for peat and lake sediments. *Ecology* 65: 657-659.

**1985**

Kutzbach JE and Wright HE. Simulation of the climate of 18,000 years BP: results for the North American/North Atlantic/European sector and comparison with the geologic record of North America. *Quaternary Science Reviews* 4: 147-187.

Wright HE. Glacial and vegetational history of southeastern Labrador. *National Geographic Society Research Reports* 20: 887-892.

Wright HE, Almendinger JC and Grüger J. Pollen diagram from the Nebraska Sandhills and the age of the dunes. *Quaternary Research* 24: 115-120.

**1986**

Tarapchak SJ and Wright HE. Effects of forest fire and other disturbances on wilderness lakes in northeastern Minnesota, I: Limnology. *Archiv für Hydrobiologie* 106: 177-202.

Wright HE. Faunal extinctions at the end of the Pleistocene. *Reviews in Anthropology* 13: 223-225.

Wright HE. Sedimental journey. *Minnesota* May/June 1986: 42-43.

Wright HE. Book Review: Handbook of Holocene palaeoecology and palaeohydrology, by B.E. Berglund et al. *Science* 233: 482.

Wright HE. Book Review: Quaternary geology and environment of China. *Science* 231: 874.

**1987**

Barnosky CW, Grimm EC and Wright HE. Towards a postglacial history of the northern Great Plains: a review of the paleoecological problems. *Annals of Carnegie Museum* 56: 259-273.

Hansen BCS and Wright HE. The modern pollen rain of North Dakota. *Pollen et Spores* 29: 167-184.

Ruddiman WF and Wright HE (eds). *North America and Adjacent Oceans During the Last Deglaciation* (The Geology of North America, Volume K-3). Geological Society of America, 501 pp.

Ruddiman WF and Wright HE. Introduction. In: Ruddiman WF and Wright HE (eds) *North America and Adjacent Oceans During the Last Deglaciation* (The Geology of North America, Volume K-3)*.* Boulder, Colorado: Geological Society of America, 1-12.

Wright HE. Synthesis: the land south of the ice sheet. In: Ruddiman WF and Wright HE (eds) *North America and Adjacent Oceans During the Last Deglaciation* (The Geology of North America, Volume K-3)*.* Boulder, Colorado: Geological Society of America, 479-488.

**1988**

COHMAP Members. Climatic changes of the last 18,000 years: observations and model simulations. *Science* 241: 1043-1052.

Foster DR, Wright HE, Thelaus M and King GA. Bog development and landform dynamics in central Sweden and south-eastern Labrador, Canada. *Journal of Ecology* 76: 1164-1185.

**1989**

Johnson RG and Wright HE. Great Basin calcite vein and the Pleistocene time scale. *Science* 246: 262-263.

Wright HE. Origin and development of Minnesota lakes. *Journal of the Minnesota Academy of Sciences* 55: 26-31.

Wright HE. The amphi-Atlantic distribution of the Younger Dryas paleoclimatic oscillation. *Quaternary Science Reviews* 8: 295-306.

Wright HE. The Quaternary. In: Bally AW and Palmer AR (eds) *The Geology of North America, vol. A. An Overview.* Boulder, Colorado: Geological Society of America, 513-536.

Wright HE, Seltzer GO and Hansen BCS. Glacial and climatic history of the central Peruvian Andes. *National Geographic Research* 5: 439-445.

**1990**

Anfinson SF and Wright HE. Climatic change and culture in prehistoric Minnesota. In: Gibbon GE (ed) *The Woodland Tradition in the Western Great Lakes: Papers Presented to Elden Johnson.* Minneapolis: University of Minnesota Publications in Anthropology, 213-232.

Engstrom DR, Hansen BCS and Wright HE. A possible Younger Dryas record in southeastern Alaska. *Science* 250: 1383-1385.

Farrand WR, Stein JK and Wright HE. Presentation of the Archaeological Geology Division Award to HE Wright Jr. *Geological Society of America Bulletin* 102: 1144-1146.

Foster DR and Wright HE. Role of ecosystem development and climate change in bog formation in central Sweden. *Ecology* 71: 450-463.

Wright HE. An improved Hongve sampler for surface sediments. *Journal of Paleolimnology* 4: 91-92.

Wright HE. Geologic history of Minnesota rivers. *Minnesota Geological Survey* Educational Series 7: 1-20.

**1991**

Engstrom DR, Whitlock C, Fritz SC and Wright HE. Recent environmental change inferred from the sediments of small lakes in Yellowstone's northern range. *Journal of Paleolimnology* 5: 139-174.

Eyster-Smith NM, Wright HE and Cushing EJ. Pollen studies at Lake St. Croix, a river lake on the Minnesota/Wisconsin border, USA. *The Holocene* 1: 103-109.

Seltzer GO and Wright HE. Deglaciation in Peru and Bolivia since the late Pleistocene \[in Spanish with English summary\]. *Boletin de al Sociedad Geological Boliviana* 26: 13-32.

Wright HE. Coring tips. *Journal of Paleolimnology* 6: 37-49.

Wright HE. Environmental conditions for Paleoindian immigration. In: Dillehay TD and Meltzer DJ (eds) *The First Americans: Search and Research.* Boca Raton, Florida: CRC Press, 113-136.

**1992**

Wright HE. Introduction. In: Wright HE, Coffin BA and Aaseng NE (eds) *The Patterned Peatlands of Minnesota.* Minneapolis: University of Minnesota Press, xv-xx.

Wright HE. Lakes as environmental archives: some case studies from the Minnesota area. *Sveriges Geologiska Undersökning Series C* 81: 373-380.

Wright HE. Patterns of Holocene climatic change in the midwestern United States. *Quaternary Research* 38: 129-134.

Wright HE, Coffin B and Aaseng NE (eds). *The Patterned Peatlands of Minnesota.* Minneapolis: University of Minnesota Press, 327 pp.

**1993**

Kutzbach JE, Bartlein PJ, Prentice IC, Ruddiman WF, Street-Perrott FA, Webb T and Wright HE. Epilogue. In: Wright HE, Kutzbach JE, Ruddiman WF, Street-Perrott FA, Bartlein PJ (eds) *Global Climates Since the Last Glacial Maximum.* Minneapolis: University of Minnesota Press, 536-542.

Roberts N and Wright HE. Vegetational, lake-level, and climatic history of the Near East and southwest Asia. In: Wright HE, Kutzbach JE, Webb T, et al. (eds) *Global Climates Since the Last Glacial Maximum.* Minneapolis: University of Minnesota, 194-220.

Webb T, Ruddiman WF, Street-Perrott FA, Markgraf V, Kutzbach JE, Bartlein PJ, Wright HE and Prell WL. Climatic changes during the past 18,000 years: regional syntheses, mechanisms, and causes. In: Wright HE, Kutzbach JE, Ruddiman WF, Street-Perrott FA, Bartlein PJ (eds) *Global Climates Since the Last Glacial Maximum.* Minneapolis, Minnesota: University of Minnesota Press, 514-535.

Wright HE. Core compression. *Limnology and Oceanography* 38: 699-401.

Wright HE. Environmental determinism in Near Eastern prehistory. *Current Anthropology* 34: 458-469.

Wright HE. History of the landscape in the Itasca region. In: Bradbury JP and Dean WE (eds) *Elk Lake, Minnesota: Evidence for Rapid Climate Change in the North-Central United States.* Geological Society of America Special Paper 276, 7-17.

Wright HE. Introduction. In: Wright HE, Kutzbach JE, Ruddiman WF, Street-Perrott FA, Bartlein PJ (eds) *Global Climates Since the Last Glacial Maximum.* Minneapolis: University of Minnesota Press, 1-4.

Wright HE and Bartlein PJ. Reflections on COHMAP. *The Holocene* 3: 89-92.

Wright HE, Kutzbach JE, Webb T, Ruddiman WF, Street-Perrott FA and Bartlein PJ (eds). *Global Climates Since the Last Glacial Maximum*. Minneapolis: University of Minnesota Press, 569 pp.

**1994**

Engstrom DR, Whitlock C, Fritz S and Wright HE. Reply: Reinventing erosion in Yellowstone's northern range. *Journal of Paleolimnology* 10: 159-161.

Hansen BCS, Seltzer GO and Wright HE. Late Quaternary vegetational change in the central Peruvian Andes. *Palaeogeography Palaeoclimatology Palaeoecology* 109: 263-285.

Wright HE. *Historical notes on the Limnological Research Center*. http://lrc.geo.umn.edu/history.html#history

**1995**

Arkhipov SA, Ehlers J, Johnson RG and Wright HE. Glacial drainage towards the Mediterranean during the middle and late Pleistocene. *Boreas* 24: 196-206.

Wright HE and Clark JS. Charcoal analysis of varved lake sediments. In: Miller U and Hicks S (eds) *Laminated Sediments in Archaeology: Archives of Environmental History.* Ravello, Italy: European Centre for Cultural Heritage, 125-130.

**1996**

Ahlberg K, Almgren E, Wright HE, Ito E and Hobbie S. Oxygen-isotope record of Late-Glacial climatic change in western Ireland. *Boreas* 25: 257-267.

Berglund BE, Birks HJB, Ralska-Jasiewiczowa M and Wright HE. (eds). *Palaeoecological Events During the Last 15000 Years: regional syntheses of palaeoecological studies of lakes and mires*. Chichester: J. Wiley & Sons, 764 pp.

Birks HH, Battarbee RW, Beerling DJ, et al. The Krakenes late-glacial palaeoenvironmental project. *Journal of Paleolimnology* 15: 281-286.

Wright HE. Global climatic changes since the last glacial maximum: Evidence from paleolimnology and paleoclimate modeling. *Journal of Paleolimnology* 15: 119-127.

Wright HE. Breakthroughs in Ice-Age history. Speech given to the College of Biological Science, University of Minnesota, 6 April 1996.

**1997**

Hu FS, Wright HE, Ito E and Lease K. Climatic effects of Glacial Lake Agassiz in the midwestern United States during the last deglaciation. *Geology* 25: 207-210.

**1998**

Patterson CJ and Wright HE (eds). *Contributions to Quaternary Studies in Minnesota*. Minnesota Geological Survey Report of Investigations 49, 208 pp.

Wright HE, Lease K and Johnson S. Glacial River Warren, Lake Pepin, and the environmental history of southeastern Minnesota. In: Patterson CJ and Wright HE (eds) *Contributions to Quaternary Studies in Minnesota.* Minnesota Geological Survey Report of Investigations 49, 131-140.

**1999**

Hu FS, Slawinski D, Wright HE, et al. Abrupt changes in North American climate during early Holocene times. *Nature* 400: 437-440.

**2000**

Birks HH and Wright HE (eds). Special Issue: The Reconstruction of the Late-Glacial and Early-Holocene Aquatic Ecosystems in Kråkenes Lake, Norway. *Journal of Paleolimnology* 23, 115.

Birks HH and Wright HE. Introduction to the reconstruction of the late-glacial and early-Holocene aquatic ecosystems at Kråkenes Lake, Norway. *Journal of Paleolimnology* 23: 1-5.

Wright HE. Origin of the climate and vegetation of the Mediterranean area. In: Arsebük G, Melink MJ and Schirmer W (eds) *Light on Top of the Hill. Studies presented to Halet Cambel.* Istanbul: Ege Publishing, 765-774.

**2001**

Ahlberg K, Almgren E, Wright HE, et al. Holocene stable-isotope stratigraphy at Lough Gur, County Limerick, western Ireland. *The Holocene* 11: 367-372.

Blyakharchuk TA, Stefanova I, Wright HE and Ammann B. Paleoenvironmental reconstructions for mountains in the Eurasian mid-continent. *PAGES News* 9: 11-13.

Snyder JA, Wasylikowa K, Fritz SC and Wright HE. Diatom-based conductivity reconstruction and palaeoclimatic interpretation of a 40-ka record from Lake Zeribar, Iran. *The Holocene* 11: 737-745.

Stevens LR, Wright HE and Ito E. Proposed changes in seasonality of climate during the Lateglacial and Holocene at Lake Zeribar, Iran. *The Holocene* 11: 747-755.

Yu Z and Wright HE. Response of interior North America to abrupt climate oscillations in the North Atlantic region during the last deglaciation. *Earth-Science Reviews* 52: 333-369.

**2002**

Engstrom DR and Wright HE. Sedimentological effects of aeration-induced lake circulation. *Lake and Reservoir Management* 18: 201-214.

**2003**

Blyakharchuk TA, Wright HE, Borodavko PS, et al. The development of the landscape of the central Altai Mountains in the late Glacial and Holocene according to pollen data from three lakes on the Ulagan plateau. *Palaeogeography Palaeoclimatology Palaeoecology* 209: 259-279.

Seltzer GO, Rodbell DT and Wright HE (eds). Special Issue: Late Quaternary Paleoclimates of the Southern Tropical Andes and Adjacent Regions. *Palaeogeography, Palaeoclimatology, Palaeoecology* 194, 338 pp.

Stefanova I and Wright HE. Holocene vegetational changes in Minnesota, midwestern United States. *Phytologia Baltica* 9: 249-252.

Wright HE and Thorpe JL. Climatic change and the origin of agriculture in the Near East. In: Mackay AW, Battarbee RW, Birks HJB, et al. (eds) *Global Change in the Holocene.* London: Arnold, 49-62.

Wright HE, Ammann B, Stefanova I, et al. Late-glacial and early-Holocene dry climates from the Balkan Peninsula to southern Siberia. In: Tonkov S (ed) *Aspects of Palynology and Paleoecology. Festschrift in honor of Elissaveta Bozilova.* Sofia: Pensoft Publishing, 249-252.

**2004**

Blyakharchuk TA, Wright HE, Borodavko PS, et al. Late Glacial and Holocene vegetational changes on the Ulagan high-mountain plateau, Altai Mountains, southern Siberia. *Palaeogeography Palaeoclimatology Palaeoecology* 209: 259-279.

Ralska-Jasiewiczowa M, Latalowa M, Wasylikowa K, et al. *Late Glacial and Holocene History of Vegetation in Poland Based on Isopollen Maps,* Krakow: W. Szafer Institute of Botany, Polish Academy of Sciences, 444 pp.

Wright HE. Pleistocene glaciation of Iraq. In: Ehlers J and Gibbard PL (eds) *Developments in Quaternary Sciences Volume 2: Quaternary Glaciations Extent and Chronology — Part III: South America, Asia, Africa, Australasia, Antarctica.* Elsevier, 215-216.

Wright HE and Stefanova I. "Plant trash" in the basal sediments of glacial lakes. *Acta Palaeobotanica* 44: 141-146.

Wright HE, Stefanova I, Tian J, et al. A chronological framework for the Holocene vegetational history of central Minnesota: the Steel Lake pollen record. *Quaternary Science Reviews* 23: 611-626.

**2005**

Wright HE. Contrasts in the Quaternary of mid-North America and mid-Eurasia: notes on Quaternary landscapes of western Siberia. *Journal of Quaternary Science* 20: 813-819.

Wright HE, Blyakharchuk TA, Velichko AA and Borisova, OK (eds). *Cenozoic Climatic and Environmental Changes in Russia* (English edition). Geological Society of America Special Paper.

**2006**

Cohen D, Person M, Daannen R, et al. Groundwater-supported evapotranspiration within glaciated watersheds under conditions of climate change. *Journal of Hydrology* 320: 484-500.

Kelley DW, Brachfield SA, Nater EA and Wright HE. Sources of sediment in Lake Pepin on the upper Mississippi River in response to Holocene climatic changes. *Journal of Paleolimnology* 35: 193-206.

Stefanova I, Atanassanova J, Delcheva M and Wright HE. Chronological framework for the Late Glacial pollen and macrofossil sequence in the Pirin Mountains, Bulgaria: Lake Besbog and Lake Kremensko-5. *The Holocene* 16: 1-16.

Stefanova I, Lazarova M and Wright HE. Elevational gradients during the Late Glacial/Holocene vegetational transition. *Vegetation History and Archaeobotany* 15: 215-230.

Stevens LR, Ito E, Schwalb A and Wright HE. Timing of atmospheric precipitation in the Zagros Mountains inferred from a multi-proxy record from Lake Mirabad, Iran. *Quaternary Research* 66: 494-500.

Westover KS, Fritz SC, Blyakharchuk TA and Wright HE. Diatom paleolimnological record of Holocene climatic and environmental change in the Altai Mountains, Siberia. *Journal of Paleolimnology* 33: 519-541.

Wright HE. Climate and biota of eastern North America. In: Ubelaker DW (ed) *Handbook of North American Indians, Volume 3: Environment, Origins, and Populations.* Washington: Smithsonian Institution, 99-109.

**2007**

Blyakharchuk TA, Wright HE, Borodavko PS, et al. Late Glacial and Holocene vegetational history of the Altai Mountains (southwestern Tuva Republic, Siberia). *Palaeogeography Palaeoclimatology Palaeoecology* 245: 518-534.

Person M, Roy P, Wright HE, et al. Hydrologic response of the Crow Wing watershed, Minnesota to mid-Holocene climate change. *Geological Society of America Bulletin* 119: 363-376.

**2008**

Blyakharchuk TA, Wright HE, Borodavko PS, et al. The role of pingos in the development of the Dzhangyskol lake-pingo complex, central Altai Mountains, southern Siberia. *Palaeogeography Palaeoclimatology Palaeoecology* 257: 404-420.

Stevens LR, Ito E and Wright HE. Variations in effective moisture at Lake Zeribar during the last glacial period and Holocene inferred from the δ^18^O values of authigenic calcite. In: Wasylikowa K and Witkowski A (eds) *The Palaeoecology of Lake Zeribar and Surrounding Areas, Western Iran, During the Last 48,000 Years.* Ruggell: ARG Gantner Verlag KG, Diatom Monographs 8, 283-302.

Wasylikowa K and Wright HE. Description of sediments. In: Wasylikowa K and Witkowski A (eds) *The Palaeoecology of Lake Zeribar and Surrounding Areas, Western Iran, During the last 48,000 Years.* Ruggell: ARG Gantner Verlag KG, Diatom Monographs 8, 37-41.

Wasylikowa K, van Zeist W, Wright HE, et al. The Lake Zeribar palaeoecology: a synthesis. In: Wasylikowa K and Witkowski A (eds) *The Palaeoecology of Lake Zeribar and Surrounding Areas, Western Iran, During the Last 48,000 Years.* Ruggell: ARG Gantner Verlag KG, Diatom Monographs 8, 303-322.

Wright HE. Geologic and climatic setting of the sites. In: Wasylikowa K and Witkowski A (eds) *The Palaeoecology of Lake Zeribar and Surrounding Areas, Western Iran, During the last 48,000 Years.* Ruggell: ARG Gantner Verlag KG, Diatom Monographs 8, 17-22.

Wright HE. History of research. In: Wasylikowa K and Witkowski A (eds) *The Palaeoecology of Lake Zeribar and Surrounding Areas, Western Iran, During the last 48,000 Years* Ruggell: ARG Gantner Verlag KG, Diatom Monographs 8, 11-16.

Wright HE and Wasylikowa K. Coring and sampling methods. In: Wasylikowa K and Witkowski A (eds) *The Palaeoecology of Lake Zeribar and Surrounding Areas, Western Iran, During the last 48,000 Years.* Ruggell: ARG Gantner Verlag KG, Diatom Monographs 8, 31-37.

**2009**

Blumentritt DJ, Wright HE and Stefanova I. Formation and early history of Lakes Pepin and St. Croix in the upper Mississippi River. *Journal of Paleolimnology* 41: 545-562.

**2010**

Wright HE. High points in paleolimnological studies as viewed by a convert. *Journal of Paleolimnology* 44: 497-503.

**2011**

Jennings CE, Knaeble A, Meyer G, et al. A glacial record spanning the Pleistocene in southern Minnesota. *Geological Society of America Field Guides* 24: 351-378.

**2013**

Ammann B, van Raden UJ, Schwander J, et al. Responses to rapid warming at Termination 1a at Gerzensee (central Europe): Primary succession, albedo, soils, lake development, and ecological interactions. *Palaeogeography Palaeoclimatology Palaeoecology* 391: 111-131.

Ammann B, Wright HE, Stefanova V, et al. The role of peat decomposition in patterned mires: a case study from the central Swiss Alps. *Preslia* 85: 317-332.

Wright HE. Preface to Special Issue on "Early rapid warming". *Palaeogeography Palaeoclimatology Palaeoecology* 391: 1-2.

**2014**

Ammann B, van der Knaap WO, Lang G, et al. The potential of stomata analysis in conifers to estimate presence of conifer trees: examples from the Alps. *Vegetation History and Archaeobotany* 23: 249-264.
